In [262]:
import numpy as np
import scipy.linalg as la
import cmath
import math
j = cmath.sqrt(-1)

In [216]:
#definition of useful matrices
pauliZ = 0.5*np.array([[1,0],[0,-1]])
I = 1.0*np.array([[1,0],[0,1]])
N=2

In [217]:
#generating array for Sz for particle k, all identity exect the kth position which is pauliZ
SkZgen = np.full((N,N,2,2),I)
for i in range(N):
    SkZgen[i,i] = pauliZ

In [218]:
#creates array of SZ operators in Hilbert space of N particles
#The element of the array is which particle SZ acts on
SZ = np.zeros((N,2**N,2**N))
for i in range(N):
    SiZgen = SkZgen[i]
    SjZ = SiZgen[0]
    for k in range(N-1):
        SjZ = np.kron(SjZ,SiZgen[k+1])
    SZ[i] = SjZ

In [219]:
#Define Hamiltonian 
B = 1
A = 5
sum = np.zeros((2**N,2**N))
for i in range(N-1):
    sum = sum + np.matmul(SZ[0],SZ[i+1])
H = B*SZ[0]+A*sum
print(H)

[[ 1.75  0.    0.    0.  ]
 [ 0.   -0.75  0.    0.  ]
 [ 0.    0.   -1.75  0.  ]
 [ 0.    0.    0.    0.75]]


In [245]:
#Diagonalize 
eng = np.real(la.eig(H)[0])
basis = la.eig(H)[1]
print(eng)
print(basis)

[ 1.75 -0.75 -1.75  0.75]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [246]:
#Initial State 
psi = np.zeros([1,2**N], dtype=complex)
psi[0][0]=1+0j
print(psi)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [247]:
#Change to eigenbasis
test = np.array([[-14,-28,-44],[-7,-14,-23],[9,18,29]])




In [272]:
#Evolve
steps = 5
t = np.arange(steps)
print(t)
psit = np.zeros([steps,1,2**N], dtype=complex)
for i in range(steps):
    for k in range(2**N):
        psit[i][0][k] = e**(-j*eng[k]*t[i])
print(psit)

[0 1 2 3 4]
[[[ 1.        +0.j          1.        +0.j
    1.        +0.j          1.        +0.j        ]]

 [[-0.17824606-0.98398595j  0.73168887+0.68163876j
   -0.17824606+0.98398595j  0.73168887-0.68163876j]]

 [[-0.93645669+0.35078323j  0.0707372 +0.99749499j
   -0.93645669-0.35078323j  0.0707372 -0.99749499j]]

 [[ 0.51208548+0.85893449j -0.62817362+0.7780732j
    0.51208548-0.85893449j -0.62817362-0.7780732j ]]

 [[ 0.75390225-0.6569866j  -0.9899925 +0.14112001j
    0.75390225+0.6569866j  -0.9899925 -0.14112001j]]]


In [303]:
#expectation value of SZ0

for i in range(steps):
    psitTran = np.conjugate(np.transpose(psit[0]))
    a =np.matmul(SZ[0],psitTran, dtype=complex)
    ESZ0 = np.matmul(psit[0],psitTran, dtype=complex)
print(a)
print(psit[i])
print(ESZ0)


[[ 0.5+0.j]
 [ 0.5+0.j]
 [-0.5+0.j]
 [-0.5+0.j]]
[[ 0.75390225-0.6569866j  -0.9899925 +0.14112001j  0.75390225+0.6569866j
  -0.9899925 -0.14112001j]]
[[4.+0.j]]


In [290]:
test = ESZ0[0]
tra = np.conjugate(test)
print(test)
print(tra)

[2.19381501+0.j]
[2.19381501-0.j]
