In [225]:
import numpy as np

In [226]:
pauliZ = np.array([[1,0],[0,-1]])
I = np.array([[1,0],[0,1]])
N=3

In [233]:
SkZgen = np.full((N,N,2,2),I)
for i in range(N):
    SkZgen[i,i] = pauliZ
#generating array for Sz for particle k, all identity exect the kth position which is pauliZ

In [234]:
for i in range(N):
    SiZgen = SkZgen[i]
    SjZ = SiZgen[0]
    for j in range(N-1):
        SjZ = np.kron(SjZ,SiZgen[j+1])
    SkZ[i] = SjZ
print(SkZ)
#creates array of SkZ operators in Hilbert space of N particles


[[[ 1.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0. -1.  0.  0.  0.]
  [ 0.  0.  0.  0.  0. -1.  0.  0.]
  [ 0.  0.  0.  0.  0.  0. -1.  0.]
  [ 0.  0.  0.  0.  0.  0.  0. -1.]]

 [[ 1.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.  0.  0.]
  [ 0.  0. -1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0. -1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  0.  0. -1.  0.]
  [ 0.  0.  0.  0.  0.  0.  0. -1.]]

 [[ 1.  0.  0.  0.  0.  0.  0.  0.]
  [ 0. -1.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0. -1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  0.  0. -1.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  0.  0. -1.]]]
