In [146]:
import numpy as np
import scipy.linalg as la
import cmath

In [131]:
#definition of useful matrices
pauliZ = 0.5*np.array([[1,0],[0,-1]])
I = 1.0*np.array([[1,0],[0,1]])
N=3

In [133]:
#generating array for Sz for particle k, all identity exect the kth position which is pauliZ
SkZgen = np.full((N,N,2,2),I)
for i in range(N):
    SkZgen[i,i] = pauliZ

In [134]:
#creates array of SZ operators in Hilbert space of N particles
#The element of the array is which particle SZ acts on
SZ = np.zeros((N,2**N,2**N))
for i in range(N):
    SiZgen = SkZgen[i]
    SjZ = SiZgen[0]
    for j in range(N-1):
        SjZ = np.kron(SjZ,SiZgen[j+1])
    SZ[i] = SjZ

In [135]:
#Define Hamiltonian 
B = 1
A = 5
sum = np.zeros((2**N,2**N))
for i in range(N-1):
    sum = sum + np.matmul(SZ[0],SZ[i+1])
H = B*SZ[0]+A*sum
print(H)

[[ 3.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -2.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -3.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   2. ]]


In [136]:
#Diagonalize 
eng = la.eig(H)[0]
basis = la.eig(H)[1]
print(eng)
print(basis)

[ 3. +0.j  0.5+0.j  0.5+0.j -2. +0.j -3. +0.j -0.5+0.j -0.5+0.j  2. +0.j]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [160]:
#Initial State 
psi = np.zeros([1,2**N], dtype=complex)
psi[0][0]=1+0j
print(psi)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [161]:
#Change to eigenbasis
test = np.array([[-14,-28,-44],[-7,-14,-23],[9,18,29]])




In [164]:
#Evolve
t = np.arange(100)
psit = np.zeros([1,2**N], dtype=complex)
for i in range(N):
    psit[0][i] = cmath.exp(-j*eng[i])
print(psit)

[[0.04978707+0.j 0.60653066+0.j 0.60653066+0.j 0.        +0.j
  0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j]]
