In [7]:
from qutip import *
import numpy as np
import scipy
import cmath
import matplotlib.pyplot as plt
from numpy.random import seed
from numpy.random import rand
from itertools import product
from scipy.misc import derivative
from scipy import optimize
seed(1)

In [8]:
#Parameter Definitions
B = 0
A0 = 1

In [29]:
#Make basis and get sz values
def operatorCreation(N):
    #operator definitionis
    si = qeye(2)
    sx = 0.5*sigmax()
    sy = 0.5*sigmay()
    sz = 0.5*sigmaz()

    sx_list = []
    sy_list = []
    sz_list = []
    

    for n in range(N):
        op_list = []
        for m in range(N):
            op_list.append(si)

        op_list[n] = sx
        sx_list.append(tensor(op_list))

        op_list[n] = sy
        sy_list.append(tensor(op_list))

        op_list[n] = sz
        sz_list.append(tensor(op_list))
        
        op_list[n] = si
    id = tensor(op_list)
        
    return sx_list, sy_list, sz_list,id

operatorCreation(3)[3]
tensor([basis(2,0),basis(2,0),basis(2,0)])

tesor = []
basisState = []
basisTensor = []
for i in range(3):
    op_list = []
    for m in range(3):
        op_list.append(basis(2,0))
    for j in range(2)
    

print(basisState)

[]


In [10]:
#Construct Hamiltonian
def hamiltonian(N,B,A0):
    sx_list = operatorCreation(N)[0]
    sy_list = operatorCreation(N)[1]
    sz_list = operatorCreation(N)[2]
    H = B*sz_list[0] 
    for n in range(N-1):
        H += A0*sz_list[0]*sz_list[n+1] + A0*sx_list[0]*sx_list[n+1] + A0*sy_list[0]*sy_list[n+1]
    return H

In [11]:
#Get Ground State Energy and Wavefuntion
def groundState(H):       
    #find ground state
    groundState= H.groundstate()
    return groundState[0],groundState[1]

groundState(hamiltonian(2,B,A0))

(-0.7500000000000001,
 Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[ 0.        ]
  [ 0.70710678]
  [-0.70710678]
  [ 0.        ]])

In [14]:
#Make basis and get sz values
def basisCreation(N):
    sz_list = operatorCreation(N)[2]
    id = operatorCreation(N)[3]
    Sbasis = []
    for i in range(N):
        j in range(2):
        Sbasis.append()
    
    #get sz values for basis states
    sz = np.zeros((2**N,N), dtype = complex)
    a = [[1 for j in range(N)] for i in range(2**N)]
    for i in range(2**N):
        for j in range(N):
            #matrix element <bra|Sz|ket>
            sz[i][j] = sz_list[j].matrix_element(Sbasis[i],Sbasis[i])
    return Sbasis, sz

basisCreation(3)

([Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
  Qobj data =
  [[1.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
  Qobj data =
  [[0.]
   [1.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
  Qobj data =
  [[0.]
   [0.]
   [1.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
  Qobj data =
  [[0.]
   [0.]
   [0.]
   [1.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
  Qobj data =
  [[0.]
   [0.]
   [0.]
   [0.]
   [1.]
   [0.]
   [0.]
   [0.]
   [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
  Qobj data =
  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [1.]
   [0.]
   [0.]
   [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type 

In [13]:
#get randomized RBM parameters
def ranRBMpar(N,M):
    par = np.random.rand(2*(N+M+N*M))
    return par

In [304]:
#Function to give RBM wavefuntion
def RBM_ansatz(par,N, M):
    Sbasis = basisCreation(N)[0]
    sz = basisCreation(N)[1]
    #make parmeters complex
    num = N+M+N*M
    parC = np.vectorize(complex)(par[:num],par[num:])
    a = parC[:N]
    b = parC[N:N+M]
    W = parC[N+M:].reshape(M,N)
    expTerm = np.zeros(2**N, dtype = complex)
    coshTerm = np.zeros((M,2**N), dtype = complex)
    hidProduct = np.zeros(2**N, dtype = complex)
    psiMValues = np.zeros(2**N, dtype = complex)
    psiM = 0*Sbasis[0]

    for i in range(2**N):
        for m in range(M):
            coshTerm[m][i] = 2*np.cosh(np.dot(W[m],sz[i]) + b[m])
    hidProduct = np.prod(coshTerm, axis = 0) 
    
    for i in range(2**N):
        expTerm[i] = np.exp(np.dot(a,sz[i]))
        psiMValues[i] = expTerm[i]*hidProduct[i]
        psiM += psiMValues[i]*Sbasis[i]
    psiNorm = psiM.unit()
    print(Sbasis)
    return psiNorm

RBM_ansatz(ranRBMpar(3,2),3,2)

[Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]], Quantum object: dims = [[3, 3], [1, 1]], shape 

Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[-0.7162392 +0.4550425j ]
 [ 0.13055071+0.1558357j ]
 [ 0.34117711+0.18078896j]
 [ 0.07329126-0.06530483j]
 [-0.02691141+0.20198761j]
 [ 0.10042927+0.01836116j]
 [ 0.15100599-0.0474013j ]
 [ 0.03797317-0.03806096j]
 [ 0.        +0.j        ]]

In [270]:
#Variation Energy Definition
def varEnergy(par,N, M, H):
    psiM = RBM_ansatz(par,N, M)
    E = expect(H,psiM)
    norm = psiM.norm()**2
    Enorm = E/norm
    return Enorm

In [271]:
#Energy Partials
def gradEnergy(par,N, M,H):
    eps = 0.001
    return optimize.approx_fprime(par,varEnergy,eps, N, M,H)

In [272]:
#Gradient Descent
def gradDescent(N, M):
    par = ranRBMpar(N,M)
    H = hamiltonian(N, B, A0) 
    min = scipy.optimize.fmin_cg(varEnergy,par,args= (N,M,H),full_output=True, retall = True, disp=True)
    #Ground State
    found_gs = RBM_ansatz(min[0],N, M)
    found_gs = found_gs.unit()
    #Ground State Energy
    found_gsEnergy =varEnergy(min[0], N, M,H)

    return min, found_gs, found_gsEnergy
    
    

In [273]:
y = gradDescent(3, 3)
print(y[1])

15


Exception: Operator and state do not have same tensor structure: [2, 2, 2] and [3, 3]

In [252]:
print(y[2])

-0.7499999996575161


In [253]:
#plot energy vs iteration
numIter = len(y[0][5])
iter = np.arange(numIter)
energy = np.zeros(numIter)
for i in range(numIter):
    energy[i]= varEnergy(y[0][5][i], N, M, H)
plt.plot(iter, energy)
plt.xlabel('Iteration')
plt.ylabel('Energy')
plt.title('Energy vs Iteration for N=2, M=2')
plt.hlines(-0.75,0,numIter, "r", linestyle = "--")
plt.show()


15


ValueError: operands could not be broadcast together with shapes (15,) (13,) 

In [136]:
#Error Calculation
def err(found_gs,gs,found_gsEnergy,gsEnergy):
    engErr = np.abs(found_gsEnergy-gsEnergy)
    waveFunctionErr = found_gs.trans()*gs
    waveFunctionErr = waveFunctionErr.norm()
    
    return engErr,waveFunctionErr
    

In [141]:
gradDescent(par, Sbasis, N, 3,sz, H)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [140]:
#Vary M Values
M_values = np.arange(5)
eng_values = []
print(M_values[0])

for i in range(M_values.size):
    eng = gradDescent(par, Sbasis, N, 3,sz, H)
    eng_values.append(eng)


0


ValueError: cannot reshape array of size 9 into shape (3,2)