In [37]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
from random import seed
from random import gauss
import math
from math import e
seed(1)

In [2]:
#operator definitionis
N=2
si = qeye(2)
sx = 0.5*sigmax()
sy = 0.5*sigmay()
sz = 0.5*sigmaz()

In [11]:
#make list of tensor products
sx_list = []
sy_list = []
sz_list = []

for n in range(N):
    op_list = []
    for m in range(N):
        op_list.append(si)

    op_list[n] = sx
    sx_list.append(tensor(op_list))

    op_list[n] = sy
    sy_list.append(tensor(op_list))

    op_list[n] = sz
    sz_list.append(tensor(op_list))

In [12]:
#Construct Hamiltonian
B = 0
A0 = 1
H = B*sz_list[0] 
for n in range(N-1):
    H += A0*sz_list[0]*sz_list[n+1] + A0*sx_list[0]*sx_list[n+1] + A0*sy_list[0]*sy_list[n+1]
print(H)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25  0.    0.    0.  ]
 [ 0.   -0.25  0.5   0.  ]
 [ 0.    0.5  -0.25  0.  ]
 [ 0.    0.    0.    0.25]]


In [13]:
#Find Groundstate
H.groundstate()

(-0.7500000000000001,
 Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[ 0.        ]
  [ 0.70710678]
  [-0.70710678]
  [ 0.        ]])

In [77]:
#RBM Representation
M = 1
alp = M/N

#Define RBM Parameters
a = [1 for j in range(N)]
b = [1 for i in range(M)]
W = [[1 for j in range(N)] for i in range(M)]


#Define Ansatz
visibleSum = Qobj()
for j in range(N):
    visibleSum += a[j]*sz_list[j]
    
Fi = []
hiddenSum = Qobj()
WSum = Qobj()
for i in range(M):
    for j in range(N):
        WSum += W[i][j]*sz_list[j]
        print(WSum)
    hiddenSum += b[i]+WSum
negHiddenSum = -1*hiddenSum
    
    

psi = visibleSum.expm()*(hiddenSum.expm + negHiddenSum.expm)
print(hiddenSum)


Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.5  0.   0.   0. ]
 [ 0.   0.5  0.   0. ]
 [ 0.   0.  -0.5  0. ]
 [ 0.   0.   0.  -0.5]]
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]


TypeError: unsupported operand type(s) for +: 'method' and 'method'

In [7]:
#Gradient Descent 

In [ ]:
#Ground State Wavefunction